
all:
  hosts:
    3.10.142.213:
    35.178.55.96:
    10.0.1.234:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/i_dont_give_a_ssh.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

bastion:
  hosts:
     3.10.142.213:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/i_dont_give_a_ssh.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

jenkins:
  hosts:
    35.178.55.96:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/i_dont_give_a_ssh.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

testvm:
  hosts:
    10.0.1.234:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/i_dont_give_a_ssh.pem"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/i_dont_give_a_ssh.pem -W %h:%p -q 3.10.142.213"'


